# ------------------------------------------------------------------------------
# Pull base image
FROM fullaxx/ubdev
MAINTAINER Brett Kuskie <fullaxx@gmail.com>

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND noninteractive

# libpcap0.8-dbg is not available in jammy
# ------------------------------------------------------------------------------
# Create a docker image suitable for development
RUN apt-get update && \
    apt-get install -y \
      bash-completion \
      cgdb \
      cmake \
      file \
      less \
      libnet1-dbg \
      lsof \
      meson \
      openssh-client \
      sshfs \
      tcpdump \
      tree \
      xxd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Define default entrypoint
CMD ["/bin/bash"]
